#!/usr/bin/env node
/**
 * Rebuild `types/database.ts` from the schema, for the tables this repository owns.
 *
 * The real file is generated by `supabase gen types`. This is not that, and it does
 * not pretend to be: it cannot see the linked project, so it works from a copy of
 * the schema pasted into this file. That copy was read out of `pg_attribute` and
 * checked column by column, and `map:types` compares this output against the live
 * schema whenever the Supabase MCP is available.
 *
 * It exists because hand-editing the generated file went wrong three times in one
 * session - a block inserted outside `Tables`, a block duplicated, a closing brace
 * left behind - and every version typechecked until it did not. The lesson was not
 * to be careful with the editor; it was that the ordering, the optionality rules and
 * the Relationships arrays are all mechanical, so a human should not be doing them.
 *
 * Usage: node scripts/generate-types.mjs
 */
import { writeFileSync } from "node:fs";

/**
 * Postgres type to TypeScript, the way `supabase gen types` maps them.
 *
 * Named for the SQL type rather than the TypeScript one so this file reads as a copy
 * of the schema. An unmapped type throws rather than passing through, because a
 * column typed as `uuid` would compile as a bare identifier and fail somewhere far
 * from here.
 */
const SQL_TO_TS = {
  uuid: "string",
  text: "string",
  integer: "number",
  bigint: "number",
  "double precision": "number",
  boolean: "boolean",
  "timestamp with time zone": "string",
  jsonb: "Json",
};

const T = (sqlType, nullable = false) => {
  const ts = SQL_TO_TS[sqlType];
  if (ts === undefined) throw new Error(`generate-types: unmapped SQL type "${sqlType}"`);
  return nullable ? `${ts} | null` : ts;
};

// name, type, notNull, { identity, generated }
const TABLES = {
  analyses: {
    id: T("uuid"),
    organization_id: T("text"),
    project_id: T("uuid"),
    status: T("text"),
    created_at: T("timestamp with time zone"),
    commit_sha: T("text", true),
    finished_at: T("text", true),
    error: T("text", true),
    stage: T("text", true),
    stage_at: T("text", true),
    stage_message: T("text", true),
  },
  coverage: {
    analysis_id: T("uuid"),
    organization_id: T("text"),
    files_found: T("integer"),
    files_parsed: T("integer"),
    files_skipped: T("integer"),
    distinct_folders: T("integer"),
    imports_total: T("integer"),
    imports_resolved: T("integer"),
    imports_outside: T("integer"),
    imports_excluded: T("integer"),
    imports_unresolved: T("integer"),
    resolved_fraction: { type: T("double precision", true), generated: true },
    created_at: T("timestamp with time zone"),
  },
  edges: {
    id: T("uuid"),
    organization_id: T("text"),
    analysis_id: T("uuid"),
    from_file_id: T("uuid"),
    to_file_id: T("uuid"),
    kind: T("text"),
    specifier: T("text", true),
    created_at: T("timestamp with time zone"),
    line: T("integer", true),
  },
  explanations: {
    id: T("uuid"),
    organization_id: T("text"),
    analysis_id: T("uuid"),
    file_id: T("uuid"),
    body: T("text"),
    model: T("text"),
    created_at: T("timestamp with time zone"),
  },
  file_roles: {
    id: T("uuid"),
    organization_id: T("text"),
    analysis_id: T("uuid"),
    file_id: T("uuid"),
    role: T("text"),
    source: T("text"),
    created_at: T("timestamp with time zone"),
  },
  files: {
    id: T("uuid"),
    organization_id: T("text"),
    analysis_id: T("uuid"),
    path: T("text"),
    language: T("text", true),
    fan_in: T("integer"),
    fan_out: T("integer"),
    created_at: T("timestamp with time zone"),
    folder: T("text"),
    lines: T("integer", true),
    module_id: T("text", true),
    sha256: T("text", true),
    is_entry_point: T("boolean"),
    is_external_module: T("boolean"),
  },
  insights: {
    id: T("uuid"),
    organization_id: T("text"),
    analysis_id: T("uuid"),
    file_id: T("uuid", true),
    kind: T("text"),
    title: T("text"),
    body: T("text"),
    created_at: T("timestamp with time zone"),
  },
  organizations: {
    id: T("text"),
    name: T("text"),
    created_at: T("timestamp with time zone"),
  },
  projects: {
    id: T("uuid"),
    organization_id: T("text"),
    name: T("text"),
    repo_url: T("text"),
    created_at: T("timestamp with time zone"),
  },
  routes: {
    id: T("uuid"),
    organization_id: T("text"),
    analysis_id: T("uuid"),
    file_id: T("uuid"),
    method: T("text"),
    path: T("text"),
    created_at: T("timestamp with time zone"),
  },
  skipped_files: {
    id: { type: T("integer"), identity: true },
    analysis_id: T("uuid"),
    organization_id: T("text"),
    path: T("text"),
    entry_kind: T("text"),
    reason: T("text"),
    created_at: T("timestamp with time zone"),
  },
  unresolved_imports: {
    id: { type: T("integer"), identity: true },
    analysis_id: T("uuid"),
    organization_id: T("text"),
    file_path: T("text"),
    specifier: T("text"),
    kind: T("text"),
    reason: T("text"),
    line: T("integer"),
    import_kind: T("text"),
    created_at: T("timestamp with time zone"),
  },
};

// Columns with a database default, so an insert may leave them out. `id` on every
// table is `gen_random_uuid()` and every `created_at` is `now()`. The two
// `is_*` booleans default to false, and every coverage counter defaults to zero.
const DEFAULTS = new Set([
  "id",
  "created_at",
  "fan_in",
  "fan_out",
  "is_entry_point",
  "is_external_module",
  "files_found",
  "files_parsed",
  "files_skipped",
  "distinct_folders",
  "imports_total",
  "imports_resolved",
  "imports_outside",
  "imports_excluded",
  "imports_unresolved",
]);

// Every foreign key in the schema, in the shape the generator emits.
const FOREIGN_KEYS = {
  analyses: [
    ["analyses_organization_id_fkey", "organization_id", "organizations", false],
    ["analyses_project_id_fkey", "project_id", "projects", false],
  ],
  coverage: [
    ["coverage_analysis_id_fkey", "analysis_id", "analyses", true],
    ["coverage_organization_id_fkey", "organization_id", "organizations", false],
  ],
  edges: [
    ["edges_analysis_id_fkey", "analysis_id", "analyses", false],
    ["edges_from_file_id_fkey", "from_file_id", "files", false],
    ["edges_organization_id_fkey", "organization_id", "organizations", false],
    ["edges_to_file_id_fkey", "to_file_id", "files", false],
  ],
  explanations: [
    ["explanations_analysis_id_fkey", "analysis_id", "analyses", false],
    ["explanations_file_id_fkey", "file_id", "files", true],
    ["explanations_organization_id_fkey", "organization_id", "organizations", false],
  ],
  file_roles: [
    ["file_roles_analysis_id_fkey", "analysis_id", "analyses", false],
    ["file_roles_file_id_fkey", "file_id", "files", true],
    ["file_roles_organization_id_fkey", "organization_id", "organizations", false],
  ],
  files: [
    ["files_analysis_id_fkey", "analysis_id", "analyses", false],
    ["files_organization_id_fkey", "organization_id", "organizations", false],
  ],
  insights: [
    ["insights_analysis_id_fkey", "analysis_id", "analyses", false],
    ["insights_file_id_fkey", "file_id", "files", false],
    ["insights_organization_id_fkey", "organization_id", "organizations", false],
  ],
  organizations: [],
  projects: [["projects_organization_id_fkey", "organization_id", "organizations", false]],
  routes: [
    ["routes_analysis_id_fkey", "analysis_id", "analyses", false],
    ["routes_file_id_fkey", "file_id", "files", false],
    ["routes_organization_id_fkey", "organization_id", "organizations", false],
  ],
  skipped_files: [
    ["skipped_files_analysis_id_fkey", "analysis_id", "analyses", false],
    ["skipped_files_organization_id_fkey", "organization_id", "organizations", false],
  ],
  unresolved_imports: [
    ["unresolved_imports_analysis_id_fkey", "analysis_id", "analyses", false],
    ["unresolved_imports_organization_id_fkey", "organization_id", "organizations", false],
  ],
};

const columnsOf = (table) =>
  Object.entries(table).map(([name, spec]) => [name, typeof spec === "string" ? { type: spec } : spec]);

const isNullable = (spec) => spec.type.endsWith(" | null");

// A generated column cannot be written at all, and an identity column is filled in
// by the database. Both come out as `never` rather than as optional, because
// "optional" would let a caller pass a value the database will reject.
const unwritable = (spec) => spec.generated || spec.identity;

// On insert a column may be omitted when the database would supply it: it has a
// default, or it is nullable. On update every column may be omitted, because an
// update only names what it changes.
const optionalOnInsert = (name, spec) =>
  unwritable(spec) ? "never" : DEFAULTS.has(name) || isNullable(spec) ? "?" : "";
const optionalOnUpdate = (spec) => (unwritable(spec) ? "never" : "?");

function emitTable(name) {
  const columns = columnsOf(TABLES[name]).sort(([a], [b]) => (a < b ? -1 : 1));
  const out = [`      ${name}: {`];

  out.push("        Row: {");
  for (const [column, spec] of columns) out.push(`          ${column}: ${spec.type}`);
  out.push("        }");

  out.push("        Insert: {");
  for (const [column, spec] of columns) {
    out.push(`          ${column}${optionalOnInsert(column, spec)}: ${spec.type}`);
  }
  out.push("        }");

  out.push("        Update: {");
  for (const [column, spec] of columns) {
    out.push(`          ${column}${optionalOnUpdate(spec)}: ${spec.type}`);
  }
  out.push("        }");

  const keys = FOREIGN_KEYS[name];
  if (keys.length === 0) {
    out.push("        Relationships: []");
  } else {
    out.push("        Relationships: [");
    keys.forEach(([key, column, referenced, oneToOne], index) => {
      out.push("          {");
      out.push(`            foreignKeyName: "${key}"`);
      out.push(`            columns: ["${column}"]`);
      out.push(`            isOneToOne: ${oneToOne}`);
      out.push(`            referencedRelation: "${referenced}"`);
      out.push(`            referencedColumns: ["id"]`);
      out.push(`          }${index === keys.length - 1 ? "" : ","}`);
    });
    out.push("        ]");
  }

  out.push("      }");
  return out.join("\n");
}

const file = `export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
${Object.keys(TABLES)
  .sort()
  .map(emitTable)
  .join("\n")}
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_organization_id: { Args: never; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
`;

const target = new URL("../types/database.ts", import.meta.url);
writeFileSync(target, file, "utf8");
console.log("Wrote " + Object.keys(TABLES).length + " tables to types/database.ts");
